version: '3.8'

services:
  oai-gnb:
    container_name: oai-gnb
    image: oaisoftwarealliance/oai-gnb:2024.w40
    privileged: true
    environment:
      USE_SA_TDD_MONO: 'yes'
      GNB_NAME: oai-gnb
      MCC: '208'
      MNC: '95'
      TAC: '1'
      NSSAI_SST: '1'
      AMF_IP_ADDRESS: 172.30.0.100
      GNB_NGA_IF_NAME: eth0
      GNB_NGA_IP_ADDRESS: 172.31.0.10
      GNB_NGU_IF_NAME: eth0
      GNB_NGU_IP_ADDRESS: 172.31.0.10
    networks:
      5g_ran_net:
        ipv4_address: 172.31.0.10
      5g_core_net:

networks:
  5g_ran_net:
    external: true
    name: 5g-ran-net
  5g_core_net:
    external: true
    name: 5g-core-net
